### PR TITLE
William's lab04 submission. Added a ShiningLightBulb and LightBulb Class. 

### PR DESCRIPTION
**Pull request by UCSBWillHuang1997**
A Lightbulb is a basic bulb shape with a circle and a rectangle. 
A ShiningLightBulb is a basic bulb shape with lines to designate shining.

### CODE REVIEW

**Comment by UCSBWillHuang1997** [comment]
Made some changes in javadoc and will hopefully show up in this pull request after I pushed to origin master.

**Comment by jalexanderqed** [comment]
You are not supposed to include your build or javadoc folders in the build request. Please remove them with 

```
git rm -rf build javadoc
```

Then commit and push. This should automatically update your pull request.

**Comment by UCSBWillHuang1997** [comment]
I think I did it. Is it correct?

**Comment by jalexanderqed** [comment]
No, the `build` folder is still present. You will need to run `git rm -rf build` and commit and push to remove it.

**Pull request merged**
